trigger:
  branches:
    include:
      - main
pool:
  name: Agentpool_ashish
variables:
  - group: az login ke kiye use
stages:
  - stage: AzureLogin
    displayName: "AZ login karna h"
    jobs:
      - job: 
        displayName: az login ke liye
        steps:
          - task: AzureCLI@3
            displayName: az login 
            inputs:
              connectionType: 'azureRM'
              azureSubscription: 'pipelineservicsconnaction'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az login --service-principal -u $(client-id) -p $(secret) --tenant $(tenant-id)
                az account set --subscription $(subscription id)
          - task: AzureCLI@3
            displayName: az accounnt status checked 
            inputs:
              connectionType: 'azureRM'
              azureSubscription: 'pipelineservicsconnaction'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: 'az account show'
          - task: TerraformInstaller@1
            displayName: Terraorm Install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment'
              backendServiceArm: 'pipelineservicsconnaction'
              backendAzureRmResourceGroupName: 'demo-rg'
              backendAzureRmStorageAccountName: 'ashishhaccount'
              backendAzureRmContainerName: 'ashishblodconatine'
              backendAzureRmKey: 'ashish.tfstatefile'
          - task: TerraformTask@5
            displayName: Terraform validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment'
          - task: TerraformTask@5
            displayName: Terraform Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment'
              environmentServiceNameAzureRM: 'pipelineservicsconnaction'
          - task: TerraformTask@5
            displayName: Terraform apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment'
              environmentServiceNameAzureRM: 'pipelineservicsconnaction'
          - task: TerraformTask@5
            displayName: Terraform destroy
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment'
              environmentServiceNameAzureRM: 'pipelineservicsconnaction'